import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/navigation";

const pretendard = localFont({ // ⬅️ add
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const GmarketSansMedium = localFont({ // ⬅️ add
  src: './fonts/GmarketSansMedium.woff',
  display: "swap",
  weight: "45 920",
  variable: "--font-GmarketSansMedium",
});

const GmarketSansBold = localFont({ // ⬅️ add
  src: './fonts/GmarketSansBold.woff',
  display: "swap",
  variable: "--font-GmarketSansBold",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${pretendard.variable} ${GmarketSansMedium.variable} ${GmarketSansBold.variable} bg-white`}>
      <body
        className="font-pretendard"
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
